# Welcome to Astrophysical Python!

Coding in Python is both useful and fun. Let's learn some basics about Variables and Libraries.


## Variables

In [2]:
x = 10

In [3]:
print(x)

10


Awesome! We just made a variable, `x` which has a value of `10`. Then, we used the function `print(arg)` which prints out whatever argument `arg` inside its parentheses.

Python also likes Scientific notation:

In [4]:
x2 = 1e1
print(x2)

10.0


Interesting - why did `print` include a `.0` this time? I mean the values must be the same, because both `x` and `x2` are equal to `10`! We can check this with a type of Boolean operator:

In [5]:
print(x==x2)

True


The operator `==` looks at the numbers on its left and right hand sides. If the values are equivalent, it returns `True`. Otherwise, it returns `False`. For example, let's add `1` to `x2` and see if that is equivalent to `x`:


In [6]:
print(x==(x2+1))

False


This makes sense, because 11 does not equal 10! In fact there is another Boolean operator, `!=` which asks just that:

In [7]:
print(x!=(x2+1))

True


Let's get back to the point though - if `x==x2`, then why did print give two different results:


In [8]:
print(x)
print(x2)

10
10.0


The answer is that `x` and `x2` have different **data types**. `x` is being stored in your computer's memory as an integer, whereas `x2` is being stored as something called a Float (short for floating point number). Using different data types is necessary because the memory of your computer is finite. If you want to know more about how data is stored in your computer, take a computer science class. For now, we just need to know different variables can have different data types. 

There are even data types that aren't numbers. For example, strings and characters are other data types:

In [9]:
myCharacter = "a"
myString = 'Hello Friend!'
print(myCharacter)
print(myString)

a
Hello Friend!


### Problem 1:

**Easy:** 
Define a variable `M_sun` and set it equal to the mass of the sun $1.989\times 10^{30} \mathrm{kg}$. Print it out.

**Medium:** 
Assuming every particle in the sun is a Hydrogen atom (with mass $1.674\times 10^{-27} \mathrm{kg}$), how many particles are in the sun? 

**Hard:**
Evaluate the validity (True/False) of this statement, and print the answer: There are more stars in our galaxy than grains of sand on the Earth. Do some research to find the values (*cough* google *cough*)


In [10]:
##Easy
M_sun = 1.989e30
print(M_sun)

##Medium
mH = 1.674e-27
numParticles=M_sun/mH
print(numParticles)

##Hard
sandGrains = 7.5e17
MilkyWayStars = 5e11
print(MilkyWayStars>sandGrains)

1.989e+30
1.1881720430107527e+57
False


## Libraries

Python has many useful libraries - these libraries contain useful methods and objects for your code. Let's start with the `math` library. We can add it to our current work space using the `import` command:

In [14]:
import math as m

In [15]:
print(m.pi)

3.141592653589793


The math library has a variable, `pi` which contains the value of the constant $\pi$. Notice it only prints out the first 16 significant figures of this irrational number. This restriction is because Python is storing the variable as a floating point number with a precision of 16 significant figures. If the numbers you are working with have more than 16 significant digits, be careful using Python (or other coding languages) to do math for you!

Let's see what else `math` has to offer. Now that we have $\pi$, maybe we want to do some trigonometry. For example, what is the $\sin\frac{\pi}{2}$? 

In [16]:
print(m.sin(m.pi/2))

1.0


Some of you might prefer to work in degrees, instead of radians. Luckily, `math` has your back! Let's see what $90^\circ$ is in radians:


In [17]:
print(m.radians(90))
print(m.pi/2)
print(m.degrees(m.pi/2))

1.5707963267948966
1.5707963267948966
90.0


In the above, we used the `math.radians(deg)` method to turn an angle `deg` into its equivalent value in radians. Then we printed out $\frac{\pi}{2}$ to compare and show that $90^\circ$ does correspond to $\frac{\pi}{2}$ radians. Next, we used the `math.degrees` function to convert $\frac{pi}{2}$ radians into degrees.

#### Problem:
**Easy:**
Define a variable `alpha` and set its value to $\frac{\pi}{100}$. Print the cosine and sine of this angle.

**Medium:** 
Define a variable `beta` and set its value to $85.6^\circ$. Print the cosine and sine of the angle.

**Hard:** Show that the identity $\sin^2\theta + \cos^2 \theta = 1$ is satisfied for both of the angles above.

In [18]:
##Easy
alpha = m.pi/100
cosA = m.cos(alpha)
sinA = m.sin(alpha)
print("Sin(alpha)={0:.3e}, Sin(alpha)={1:.3e}".format(sinA,cosA))

##Medium
beta = 85.6
cosB = m.cos(m.radians(beta))
sinB = m.sin(m.radians(beta))
print("Sin(beta)={0:.3e}, Sin(beta)={1:.3e}".format(sinB,cosB))

##Hard
val = cosA**2 + sinA**2
val2 = cosB**2 + sinB**2
print(val==1,val2==1)

Sin(alpha)=3.141e-02, Sin(alpha)=9.995e-01
Sin(beta)=9.971e-01, Sin(beta)=7.672e-02
True True


Now lets do some astrophysics: we can measure the distance to a nearby star using *parallax* (see [http://hyperphysics.phy-astr.gsu.edu/hbase/Astro/para.html](http://hyperphysics.phy-astr.gsu.edu/hbase/Astro/para.html)). 

![How Parallax Works](Figures/parallax.png "How Parallax Works")

Nearby stars will appear to drift on the sky, relative to the background, as the Earth orbits the sun. If we measure the distance the star has moved on the sky over the course of the Earth's orbit, then we can calculate the distance to the star. 

We can use trigonometry to calculate the distance. The angle $p$ on the sky that the star moves is related to the distance $d$ to the star and the radius $r$ of the Earth's orbit around the sun by the following equation:

$$ d\tan(p)=r $$

We can use $r = 1 \mathrm{AU} = 1.496 \times 10^{13} \mathrm{cm}$. Additionally, the angle $p$ will be very small - usually in units of arcseconds. Arcseconds are defined by 

$$1^\circ = 60 \mathrm{arcmin} = 60^2 \mathrm{arcsec} = 3600 \mathrm{arcsec}$$

Since the star will move only a few arcseconds, or even just milliarcseconds, we can use the small angle approximation and say $\tan(p) \approx p (\mathrm{radians})$. Then, the distance to the star is 

$$ d=\frac{1.496 \times 10^{13} \mathrm{cm}}{p (\mathrm{radians})} = \frac{1.496 \times 10^{13} \mathrm{cm}}{p (\mathrm{degrees})} \frac{180}{\pi} = \frac{1.496 \times 10^{13} \mathrm{cm}}{p (\mathrm{arcsec})}\frac{3600}{1} \frac{180}{\pi}$$

$$ d=\frac{3.086\times 10^{18} \mathrm{cm}}{p (\mathrm{arcsec})}$$

With the above, astronomers define a parallax arcsecond, or **parsec**, as $3.086\times 10^{18} \mathrm{cm}$. So, the distance to another star in parsecs is given by 

$$ d=\frac{1 \mathrm{pc}}{p (\mathrm{arcsec})}$$



You don't have to remember this number. There is another library, `astropy`, specifically submodules `astropy.constants` and `astropy.units`.  

In [22]:
import astropy.constants as c
import astropy.units as u
print((1.0*u.au).to('cm')) #Print the length of 1 AU in centimeters
print((1.0*u.pc).to('cm')) #Print the length of 1 parsec in centimeters

14959787070000.0 cm
3.085677581491367e+18 cm


Alright, now we need some data, specifically, the stellar parallax! Using that, we can calculate the distance to stars!

In the next lesson, we'll go over data structures in depth. For now, just know that the NumPy library allows us to calculate a lot of things at once by putting our data into *arrays*. Below, I create an array with the stellar parallax for many stars.


In [27]:
import numpy as np
Stars = np.array(["Sirius","Betelgeuse","Proxima Centauri"])
parallax = np.array([0.3792,0.00595,0.76813])*u.arcsec
#Parallax is in arcsec here,
#note the combined use of AstroPy and NumPy. Libraries are often compatible

distance = 1.0*u.pc/(parallax/u.arcsec)
print(Stars)
print(distance.to("pc"))
        

['Sirius' 'Betelgeuse' 'Proxima Centauri']
[  2.6371308  168.06722689   1.30186297] pc


#### Problem:

**Easy**
Print the length of a lightyear in centimeters using the `astropy` library.

**Medium**
Print the distance to each star in `parallax` in units of lightyears, instead of parsecs.

**Hard**
Sort the `parallax` array from nearest to furthest star. 

In [41]:
##Easy
print((1*u.lyr).to('cm'))

##Medium
print(Stars)
print(distance.to("lyr"))

##Hard
print(np.sort(distance))


9.4607304725808e+17 cm
['Sirius' 'Betelgeuse' 'Proxima Centauri']
[  8.6011703  548.16197936   4.24610909] lyr
[  1.30186297   2.6371308  168.06722689] pc
